import React from "react";
import Head from "next/head";

function contact() {
  return (
    <>
      <Head>
        <title>MeekDeco Furniture Store - About us</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>contact</main>
    </>
  );
}

export default contact;
