import Head from "next/head";
import { Manrope } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { NavBar } from "@/export/allComps";

const manrope = Manrope({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MeekDeco Furniture Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style jsx global>{`
          html {
            font-family: ${manrope.style.fontFamily};
          }
        `}</style>
      </Head>
      <main className={styles.main}>
        {/* <NavBar /> */}

        <h2> HomePage</h2>
      </main>
    </>
  );
}
