import Head from "next/head";
import React from "react";

function Products() {
  return (
    <>
      <Head>
        <title>MeekDeco Furniture Store - About us</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main></main>
    </>
  );
}

export default Products;
